services:
  zookeeper:
    container_name: zookeeper
    restart: always
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/wurstmeister"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  server-broker:
    container_name: server-broker
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
volumes:
  kafka-volume:
  zookeeper-volume: